### ISSUE TITLE
Does not reload

### ISSUE THREAD

**Issue by TheBartoMan** [marthoc/homeseer#83]
If you click reload on the Homeseer integration, it will never reload, you just get "Failed to setup"

The only way you can get the Homeseer integration to work again is to restart Home Assistant.

Even when the Homeseer integration is working, if you try to click reload, you then get failed to setup and you have no other choice other that to restart home assistant?

Why does reload not work / break the integration?

**Comment by wpiman** [comment]
I am experiencing something similar.  I can load the plugin on the latest version of HA it imports all my homeseer devices.  Works awesome.  When I reload home assistant-- it failed to load unless I delete the config/lsiopy directory.  I still see errors in the log but it works.

I run on Docker-- and from what I gather is the async directory that is imported here is now integrated into latest version of python...  Home Assistant runs 3.11 of pythonnow.

Not sure if just the "import async" needs to go away or if other stuff needs to change....

  File "/lsiopy/lib/python3.11/site-packages/homeassistant/core.py", line 1650, in async_set
homeassistant    |     state = State(
homeassistant    |             ^^^^^^
homeassistant    |   File "/lsiopy/lib/python3.11/site-packages/homeassistant/core.py", line 1266, in __init__
homeassistant    |     raise InvalidStateError(
homeassistant    | homeassistant.exceptions.InvalidStateError: Invalid state encountered for entity ID: sensor.blplex_blplex_subscriptionfeatures. State max length is 255 characters.
homeassistant    | 2023-09-05 21:06:58.046 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up homeseer platform for sensor
homeassistant    | Traceback (most recent call last):
homeassistant    |   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 370, in _async_setup_platform
homeassistant    |     await asyncio.gather(*pending)
homeassistant    |   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
homeassistant    |     await asyncio.gather(*tasks)
homeassistant    |   File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 750, in _async_add_entity
homeassistant    |     await entity.add_to_platform_finish()

**Comment by yapatek** [comment]
Is this integration still supported? This is my first time attempting an installation. It is indeed a very useful Integration.

I also get the error “Failed to setup” after it confirms a successful installation. Reloading or rebooting HA does not help. Multiple removal and installation resulted the same outcome. 

What I noticed was that there was an existing Integration using the same name “HomeSeer” which was the newly implemented official HomeSeer device support integration! Once I downloaded and installed this program, it basically replaced the official “HomeSeer” integration with the same name. Just wondering if this had anything to do with it?  

Your help and opinions are much appreciated!

Thank you!

**Comment by wpiman** [comment]
I am guessing it is not.  Posted June 22 and not a peep from the developer...
