### ISSUE TITLE
Support for HS4?

### ISSUE THREAD

**Issue by steinis123** [marthoc/homeseer#9]
Im running HS4, I get following error inn HA:

2020-09-15 19:42:42 ERROR (MainThread) [homeassistant.setup] Error during setup of component homeseer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 191, in _async_setup_component
    result = await task
  File "/config/custom_components/homeseer/__init__.py", line 82, in async_setup
    await homeseer.api.initialize()
  File "/usr/local/lib/python3.8/site-packages/pyhs3/hometroller.py", line 56, in initialize
    await self._get_devices()
  File "/usr/local/lib/python3.8/site-packages/pyhs3/hometroller.py", line 95, in _get_devices
    all_devices = result["Devices"]
KeyError: 'Devices'

Any idea if this is relatied to me running HS4 or is it something else im doing wrong?

**Comment by kmitch95120** [comment]
This error is occurring in pyhs3, not in the homeseer component.   Can you open an issue here: https://github.com/marthoc/pyhs3/issues?

Also, please add the following to your configuration.yaml file and attach the debug log to the pyhs3 issue. 
<PRE>
logger:
  default: info
  logs:
    homeassistant.core: debug
    asyncio: debug
    custom_components.homeseer: debug
    pyhs3: debug
</PRE>
Thanks,
Ken

**Comment by kmitch95120** [comment]
Preliminary testing shows this component is compatible with HS4. However, the module "pyhs3" should be checking the "Version" parameter in the API data from HS and acting appropriately. Currently this is "1.0" for both HS3 and HS4. Additional data verification and debug logging should be added to pyhs3 to better handle data errors such as the one above.
